### ISSUE TITLE
update propEqual and notPropEqual to handle Symbols properly

### ISSUE THREAD

**Issue by leobalter** [qunitjs/qunit#1009]
`propEqual` and `notPropEqual` are not handling symbols properly, they need to fixed.

``` js
QUnit.test("symbols", function(t) {
  var s1 = Symbol("QUnit");
  var s2 = Symbol("QUnit");
  t.propEqual(s1, s2, "this should not pass");
  t.notPropEqual(s1, s2, "this should pass");
  t.propEqual(s1, s1, "this should pass");
  t.notPropEqual(s1, s1, "this should not pass");
});
```

While it works for the equivalency of the same symbols, the does not for different symbols. `s1` and `s2` are different, and they are **not compared** by their description, despite it being the same. They should not be compared by their description, thou. The bug is elsewhere.

Other minor problem is the failure message reporting them as ordinary objects, they are not, they are on their own native type.

**Comment by leobalter** [comment]
It's good to fix this one with proper tests.

**Comment by trentmwillis** [comment]
I'm not sure this is a bug. `propEqual` is meant to check the properties of the two objects, but `Symbol`s are primitives without properties. I'd like it to be the same as doing `propEqual(true, true)`.

**Comment by trentmwillis** [comment]
@leobalter any thoughts here? I'm inclined to close it. Otherwise the only way I could see to check this is doing a `s1.toString() === s2.toString()` check (would reveal if they have the same description), but I think that's dangerous since Symbols have unique identities and so even if the description is the same for a Symbol, it is likely that you really want the exact instance of the Symbol, in which case you can use `assert.strictEqual`.

**Comment by trentmwillis** [comment]
I'm going to close this, but if you still feel this is needed, let's reopen and discuss.
