### ISSUE TITLE
dom inspector shows qunit-fixture not cleaned up

### ISSUE THREAD

**Issue by ozanh** [qunitjs/qunit#1071]
I am new to QUnit 2.0. While I was checking this [example ](https://qunitjs.com/cookbook/#keeping-tests-atomic)I realized that dom inspectors of firefox and chrome shows qunit-fixture not cleaned up. Is it a bug or am I missing something?

**Comment by platinumazure** [comment]
Can you please provide a more complete example, maybe on JSFiddle?

Specifically, it's not clear what your `#qunit-fixture` element actually looks like.

Also, note that the fixture is only cleaned up between tests, not in the middle of a test.

**Comment by ozanh** [comment]
Sorry, here is the [jsfiddle](https://jsfiddle.net/ozanhaci/wffuz6mn/) and I added the comments in it.

**Comment by platinumazure** [comment]
I've forked and modified the fiddle to [here](https://jsfiddle.net/7okkbtxn/1/), using `assert.async()` and a button to allow the tests to be run one at a time with the DOM being inspected in each case.

The `console.log` statements may be run before the module callback is even run, so I don't think those are very useful.

I also wouldn't be surprised if the qunit-fixture were not cleaned up after the last test, because (from the perspective of the unit tests) there would be no need.

Try playing around with my fiddle and let me know if you still see any weird behavior.

**Comment by ozanh** [comment]
Thank you for the fiddle, it seems that cleanup takes place **before** each test so updating the [documentation](https://qunitjs.com/cookbook/#keeping-tests-atomic) will be enough because it says that 

> QUnit will reset the elements inside the #qunit-fixture element **after** each test, removing any events that may have existed. As long as you use elements only within this fixture, you don't have to manually clean up after your tests to keep them atomic.

**Comment by platinumazure** [comment]
It might be that we should just say cleanup happens "between" each test. :-)

**Comment by gibson042** [comment]
Here's what I see at http://api.qunitjs.com/QUnit.config/ :
> <div>
<strong>fixture</strong> (default: <code>undefined</code>)</div>
<div>Type: <a href="http://api.jquery.com/Types/#String">String</a>
</div>
<div>
				<p>Defines the HTML content to use in the fixture container which is reset at the start of each test.</p>
				<p>By default QUnit will use whatever the starting content of <code>#quint-fixture</code> is as the fixture reset. If you do not want the fixture to be reset in between tests, set the value to <code>null</code>.</p>
			</div>

If you see anything else that needs a change, can you open an issue on [qunitjs/api.qunitjs.com](https://github.com/qunitjs/api.qunitjs.com/issues/new)?
