### ISSUE TITLE
CI breaking on Node 0.12

### ISSUE THREAD

**Issue by leobalter** [qunitjs/qunit#1077]
Of course I broke everything again.

Travis CI is breaking on Node 0.12. This passed as a [false positive](https://travis-ci.org/qunitjs/qunit/jobs/181583215#L219-L223) from #1049.

ESLint is failing on Node 0.12...

**Comment by mgol** [comment]
Hint: you need sth like the following:
https://github.com/jquery/jquery/blob/7fbab88/Gruntfile.js#L19-L24
https://github.com/jquery/jquery/blob/7fbab88/Gruntfile.js#L189-L194
https://github.com/jquery/jquery/blob/7fbab88/Gruntfile.js#L232

to make it work (basically, to turn ESLint into a noop in Node <4).

**Comment by platinumazure** [comment]
When making Travis run ESLint, I intentionally made it so it only ran on Node 6 (because we don't need to lint in every configuration since ESLint basically behaves the same on Node >=4.0 and because it's not a crucial functionality test that needs to run on all supported platforms). Please let me know if you have questions on how I did that.

**Comment by mgol** [comment]
@platinumazure QUnit uses Grunt and just configuring that on Travis is not enough. `Gruntfile.js` is loaded in all Node versions and this line:
https://github.com/qunitjs/qunit/blob/d3aaf9b/Gruntfile.js#L4
means the `eslint` task gets loaded which breaks in older Nodes as it's written in ES6.

I don't think it's feasible to rely purely on Travis here, QUnit needs the jQuery Core treatment I mentioned in my previous comment.

**Comment by platinumazure** [comment]
Thanks. Bit surprised that what I had done before worked, then...

On Dec 6, 2016 8:39 AM, "Michał Gołębiowski" <notifications@github.com>
wrote:

@platinumazure <https://github.com/platinumazure> QUnit uses Grunt and just
configuring that on Travis is not enough. Gruntfile.js is loaded in all
Node versions and this line:
https://github.com/qunitjs/qunit/blob/d3aaf9b/Gruntfile.js#L4
means the eslint task gets loaded which breaks in older Nodes as it's
written in ES6.

I don't think it's feasible to rely purely on Travis here, QUnit needs the
jQuery Core treatment I mentioned in my previous comment.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/qunitjs/qunit/issues/1077#issuecomment-265165809>, or mute
the thread

**Comment by mgol** [comment]
@platinumazure This is probably because of a Grunt update. It **was** failing before (see e.g. https://travis-ci.org/qunitjs/qunit/jobs/181557397) but there must have been a bug in Grunt that let it go on in spite of the error. Now it fails properly. :)

**Comment by platinumazure** [comment]
Well, that's a shame.

@leobalter Please let me know if there's anything that I (specifically) should be looking into.

**Comment by leobalter** [comment]
my open source time today is totally consumed to finish the report for the last TC39 meeting. I'll have some extra time again tomorrow only.
