### ISSUE TITLE
Phase out dist/ folder in favour of qunit/

### ISSUE THREAD

**Issue by platinumazure** [qunitjs/qunit#1133]
I'm a bit confused about why we maintain both a `dist/` folder (for web use and development) but also create a `qunit/` folder when releasing and/or for Node. Can we simplify this process?

Long-term, my preference would be to just export a canonical "core QUnit" file and also have wrappers for executing QUnit in different contexts. (In a different issue, I might have referred to those wrappers as "runners", to contract with "reporters".) But on top of that, it would be nice if we could keep the folder structure consistent if at all possible.

**Comment by leobalter** [comment]
cc @jzaefferer. You might now the reason for this. I honestly don't remember.

**Comment by leobalter** [comment]
@platinumazure This might become the new turtle on the tree. It's there by some reason.

**Comment by Krinkle** [comment]
@platinumazure At the moment, neither `dist/` nor `qunit/` is actually in the master branch. But they do spring into existence during local development and/or as part of the release process.

### Release

Long ago (before 1.13.0, and even longer ago when it was still part of jquery's test directory) QUnit was maintained as a single file in the `qunit/` directory.

I first moved away from this in 6f8f6c3deaea5ae836f1941c96356cbc9e0b5a1c (pull #480, issue #378).

Since then, we've no longer had a `qunit/` directory in master. However there were two uses cases relying on a `qunit/` directory:
* Use of qunit through Git submodules. (Mostly older pre-npm projects.)
* Use of qunit through Bower. (Which required files to be in Git.)

It was proposed by @jzaefferer in https://github.com/qunitjs/qunit/pull/480#issuecomment-26711602 that we keep supporting this by committing the `qunit/` build artefact into Git as part of the release process. That way it won't generally exist in Git, but we can put the release tag on a leaf-node commit (or "detached commit") outside the master branch lineage so that Bower and Git-submodule usage can still reference qunit.js without post-install build process of any sort.

We were going to keep doing that for new releases until 2.0, but I guess we forgot!

### Development

During local development, grunt will generate a distribution file in `dist/`, which is used when loading the test suite in a web browser. This is a different directory name to avoid conflicts when working on releases, and in general since they use slightly different logic to be generated (one containing a git hash, the other a version tag).

**Comment by trentmwillis** [comment]
@Krinkle thanks for the background, much appreciated!

At this point, since we ship `qunit/` as part of NPM and Bower, changing/removing it would be considered a breaking change (something to keep in mind for an eventual 3.0).

So, the question then is, do we need to keep `dist/` or can we eliminate in favor of using `qunit/` all the time? I tend to think we should be able to, though it may take some work. This would be particularly beneficial when working locally and attempting to `npm link` (or similar) into other packages.

**Comment by Krinkle** [comment]
@trentmwillis Sounds good.

I wasn't aware that we also use `qunit/` for `main` in package.json for use through `require()` in Node.js. (I would've thought that we change `main` from `dist` to `qunit` in the release commit only, and not in master. If I understand correctly, this means it's currently broken in master during local development.)

**Comment by Krinkle** [comment]
Starting from the next 2.x release, I'll publish both so that people relying on these directory structures can update their code ahead of the 3.0 release.
