### ISSUE TITLE
Reduce number of tokens needed per test

### ISSUE THREAD

**Issue by breck7** [qunitjs/qunit#1189]
## Tell us about your runtime:

* **QUnit version**: 2.3.2
* **What environment are you running QUnit in? (e.g., browser, Node)**: Browser
* **How are you running QUnit? (e.g., script, testem, Grunt)**: Script

## What are you trying to do?

I find it code smell that you need to do assert.ok/assert.equal everywhere.
I'd like to shorten that so that each test takes only 1 token, not 3 (in other words, shorten the assert.)

I did the below in my test suite and it works fine using Tap on Node.js, but breaks with qunit because const seems to change this to the block scope. Would be nice if qunit allowed this.

It definitely seems to me that it should not be necessary to have those 2 extra tokens for every test.

Code that reproduces the problem:

```js

const someTest = assert => {
  const ok = assert.ok
  ok(true)
}

```

If you have any relevant configuration information, please include that here:

## What did you expect to happen?

Test should pass.

## What actually happened?

Uncaught error.

Source: 	
TypeError: Cannot read property 'pushResult' of undefined

**Comment by breck7** [comment]
A simple workaround I employed accomplishes what I want.

It does have the limitation in that it adds an extra entry to the stack on a failed test but not a problem because I often do my debugging with node/tape.

I also just switched everything to only use strictEqual, which seems better anyway.

`QUnit.test(key, assert => {
            testTree[key]((expected, actual, message) => assert.equal(expected, actual, message))
          })`

**Comment by platinumazure** [comment]
The `assert` object has some context that the assertion methods need in order to properly process the assertion (e.g., they know what test the assertion is associated with). Calling `ok` as a bare function means the assertion method does not have a valid `this` value, which leads to the TypeError you have observed.

This would be true of any object method that you try to call as a bare function, even outside of QUnit.

We could perhaps discuss whether we could have the assertion methods be created "pre-bound" (e.g., using `Function.prototype.bind`) so that they could be called as pure functions, but my personal opinion would be that you sacrifice some readability in exchange for saving a couple of keystrokes. From my perspective, I would probably just say this is how QUnit was designed.

**Comment by Krinkle** [comment]
> ```js
> const someTest = assert => {
>   const ok = assert.ok
>   ok(true)
> }
> ```
> > `TypeError: Cannot read property 'pushResult' of undefined`

Trimming the short `assert.` prefix is not supported in this way. As @platinumazure pointed out already, you'd have to bind it first: `ok = assert.ok.bind(assert);`. You're free to do so if you prefer that.

However, the following also works.

```js
const someTest = assert => {
  assert.ok(true)
}
```

This pattern works and is preferred. For simplicity, reduced cyclomatic complexity, performance (if that matters), and for aesthetic consistency with other QUnit test suites.

The aesthetic consistency and reduced complexity are especially important in my opinion. For example when collaborating with other developers, introducing new developers on your team, and in general for the open-source community your project may be open to. It helps confusion which is greatly appreciated when reading, writing, and reviewing a lot of code on a regular basis.

Also don't forget that, this hypothetical future contributor, may very well be your future self  – after working on something else for a few months :)

**Comment by breck7** [comment]
Thanks for the thoughtful responses and great work! QUnit has been a joy to use over the years. I went ahead with my closure solution but also like the "bind" suggestion, thanks @platinumazure!
