### ISSUE TITLE
Better navigation with arrow keys

### ISSUE THREAD

**Issue by zoulja** [qunitjs/qunit#1211]
I use QUnit for testing on a specific device (based on Webkit) without keyboard and mouse (using remote control unit).
Remote control can emulate arrow keys and Enter key presses.
Please consider to improve navigation on HTML report with arrow keys.
Currently it's not possible to operate in input field, drop-down list, collapse tests and so on.

**Comment by trentmwillis** [comment]
Would you mind working on this? Since this doesn't sound like a common use case, we're unlikely to get to it any time soon, but it does sound useful.

**Comment by Krinkle** [comment]
It's not clear to me why a remote control for a web browser would not be able to scroll and otherwise interact with the input fields. An example of a non-game web page that does this correctly might help. In any event, a patch for this is definitely welcome, but I'm closing this for now as I don't expect us to work on this in the near future.
