### ISSUE TITLE
2.6.0 violated semver

### ISSUE THREAD

**Issue by getify** [qunitjs/qunit#1275]
A change was apparently made in 2.6.0 that violated semver, as far as I can tell.

In version 2.5.0, I was able to pass any non-string value to `assert.step(..)`, and it passed through as-is to the `assert.verifySteps(..)` check.

I casually upgraded from 2.5.0 to 2.6.0 not expecting any breakage, and got a surprise build failure because now there's a test failure which indicates that `assert.step(..)` must be passed only strings.

This is a fine feature, and I'm OK with it. But a minor version change shouldn't have broken my tests, if I understand semver correctly.

It was not that big of a deal, I fixed by force coercing my values to strings. But it's not a good precedent to set, and could cause bigger issues for others besides me.

**Comment by platinumazure** [comment]
Hi @getify, thanks for the issue. I apologize for the inconvenience you suffered as a result of upgrading to 2.6.0.

In this case, `assert.step` was not designed to take anything besides strings, but the fact that this wasn't enforced in 2.5.0 was an oversight. Thus, we treated this as a bug, not a breaking change. Bugfixes, as you know, are semver-patch. (However, we released as semver-minor due to new features also being in the same release.)

I regret that this happened and we will try to be more careful in future as we add new features.

**Comment by getify** [comment]
I can certainly understand the concern of deciding if any tweak is just a bug fix or a breaking change... in this case, afaik, the docs never said that `assert.step(..)` had to take strings only, so I don't think I would have ever been able to tell in 2.5.0 that I was taking advantage of a bug. Thus, I would have called this a breaking change. But alas, these are tough calls to make. Thanks.
