### ISSUE TITLE
Allow qunit command to run an html file.

### ISSUE THREAD

**Issue by izelnakri** [qunitjs/qunit#1285]
Can we run browser tests in CI mode? I see that currently there is ```qunit``` command but it seems to strangely only support node environments. I have qunit tests loaded via a static ```index.html``` file or through a server under ```http://localhost:42000```. Can we just enable qunit runners by supplying a target argument like:

```qunit index.html```
or
```qunit http://localhost:4200```

This would significantly ease all the ecosystem that is currently built around qunit. Ember-cli currently uses nasty hacks like ```testem``` to provide this behavior. My experimentation tells me this could be simply achieved without such legacy library. All I need is a direct qunit command support for html files and http servers and perhaps a configuration file to specify different headless browsers with arguments, installed google chrome being default.

**Comment by trentmwillis** [comment]
QUnit tries to remain platform agnostic as much as possible. To that end, we don't intend to ship a built-in browser launcher because integrating with even just the 4 most popular ones (Chrome, Safari, FireFox, and Edge) requires lots of maintenance, and we don't want to favor one platform over another. You have to understand how each of the browsers works as a process, setup some communication channel between the browser process and the CLI, and provide a reasonable set of options to configure the browsers as they run test files.

It is actually a complex problem space and this is why tools like Testem and Karma exist. If you feel that those solutions are not sufficient or are too heavy-handed for what you wish to accomplish, then you should be able to build your own custom solution.

Also, please refrain from describing this or other projects as "nasty hacks", or using other disrespectful terms, unless you are the one who developed it.

**Comment by izelnakri** [comment]
I'm pleased with the improvements in the last few years on QUnit, you're partially responsible for it, so thank you!

I don't think being too nice helps when an open-source project is disastrously written, popular and results in hundreds of rarely used internal npm packages for its users. Their authors are ultimately responsible, regardless of "valuable contribution time" or if their project was useful at its inception.

I'm currently not happy with testem and I will keep calling it a nasty hack because that is what it is. I've read and implemented some part of testems source-code in my personal `mber` project, I don't agree that testem or karma is solving a complex problem anymore. I guess I will have rewrite this `testem ci` mode by myself, perhaps I can change your mind in few months when my rewrite is done. 

Anyways thanks for your response and contributions so far. I wish I didn't have add this to my todo list though. My point is simply: Qunit is a frontend testing framework, it has to support continuous integration by default in 2018.

**Comment by izelnakri** [comment]
@trentmwillis https://github.com/izelnakri/mber/commit/e2b691c04bbf5ab6872fa9b51739227858e6589a#diff-34bf4780c7c1160c22cddc907245a3c5 it took 54 lines of code to do it with puppeteer. 

I still think qunit should support this, and it should run chromium by default since it has the largest market share. Other vendors can have their version if they ship a nice API like puppeteer.
