### ISSUE TITLE
Document that assertions are not allowed after done()

### ISSUE THREAD

**Issue by jzaefferer** [qunitjs/qunit#1356]
From https://github.com/jquery/qunitjs.com/pull/84#issuecomment-56838952:

> We need to add a clear note about the auto-failing behavior of assertions that occur after the final done resolution within a test phase... at least to the API docs if not also to the Cookbook.

Should include this in the docs for `assert.async()`.

Related:
*  https://github.com/qunitjs/qunit/issues/666#issuecomment-56374136
* https://github.com/qunitjs/qunit/issues/668, https://github.com/qunitjs/qunit/pull/669

**Comment by Krinkle** [comment]
The warning "Assertion after the final 'assert.async' was resolved" was introduced in QUnit 1.16 along with the introduction of [assert.async()](https://qunitjs.com/api/assert/async/) itself. Ref https://github.com/qunitjs/qunit/issues/668, https://github.com/qunitjs/qunit/pull/669.

This warning existed up until QUnit 2.1. In QUnit 2.2, something changed that caused additional assertions to silently be ignored. In QUnit 2.3, the failure was re-introduced. In QUnit 2.4 the failure was finally removed. Ref https://github.com/qunitjs/qunit/pull/1148.

Closing this issue since assertions are done() have been allowed since 2017.

* QUnit 1.16 - Fail
  <img width="200" alt="" src="https://github.com/qunitjs/qunit/assets/156867/961bd979-039e-4b4e-b5d8-e3e29cf2b89a">
* QUnit 1.23 - Fail
  <img width="200" alt="" src="https://github.com/qunitjs/qunit/assets/156867/66f2ba7a-42c6-4b26-bec5-0fa18c4f55f3">
* QUnit 2.1 - Fail
  <img width="200" alt="" src="https://github.com/qunitjs/qunit/assets/156867/9e317dc2-466d-4bfe-9e3b-acb69ce6e47c">
* QUnit 2.2 - Pass with silent failure
  <img width="200" alt="" src="https://github.com/qunitjs/qunit/assets/156867/02ceafcb-5fd6-477d-b95e-7ed1c4233bf8">
* QUnit 2.3 - Fail again
  <img width="200" alt="" src="https://github.com/qunitjs/qunit/assets/156867/189dbae5-2007-4d90-9534-893cef60b7d2">
* QUnit 2.4 - Pass
  <img width="200" alt="" src="https://github.com/qunitjs/qunit/assets/156867/e61366bc-718c-422e-816b-9644819fde25">
* QUnit 2.21 - Pass
  <img width="200" alt="" src="https://github.com/qunitjs/qunit/assets/156867/07065d5f-8217-4dfd-b6f9-a720d54ea04e">
