### ISSUE TITLE
Can the test file name be passed in the "suitestart" and "suiteend" callback ?

### ISSUE THREAD

**Issue by muthu90ec** [qunitjs/qunit#1399]
Hi,
I have a use case where I want to print the name of the testfile before and after the test run.
For eg: if I have two test files
testFIle1.js
QUnit.test("point1", function(assert){
assert.ok(true);
});

testFile2.js
QUnit.test("point1", function(assert) {
assert.ok(true);
});

when I run qunit.js --reporter=myreporter test*.js ...I want the following printed in the console.

testStart=>filename: testFile1.js
progress: point1 pass
testEnd=>filename: testFile1.js result: pass

testStart=>filename: testFile2.js
progress: point1 pass
testEnd=>filename: testFile2.js result: pass

**Comment by Krinkle** [comment]
This isn't currently possible in QUnit because our core API is not in charge of loading the script files. That's handled by either the HTML file (via the browser) or by the CLI runner (via Node.js).

Continuing the conversation at https://github.com/js-reporters/js-reporters/issues/111. In particular I'd like to better understand how this helps you and/or other developers. Note that in the event of an issue, we always render the stack trace which includes the file path or URL to the test suites for easy reference.
