### ISSUE TITLE
New test method proposal to run a subset of tests

### ISSUE THREAD

**Issue by ventuno** [qunitjs/qunit#1434]
[`only`](https://api.qunitjs.com/QUnit/only) currently allows a test to exclusively run, preventing all other tests from running.
It is currently impossible to use `only` or any other existing methods to run _only_ a subset of tests.
Changing the way `only` works would be a breaking change, so I recommend to add a new method `some`. All tests added with `some` will run and other tests will be skipped.

### Possible implementation
https://github.com/qunitjs/qunit/pull/1435

### Alternative approaches
It is technically possible to group tests in a module and then use [`module.only`](https://api.qunitjs.com/QUnit/module#exclusive-tests), but it is not quite as ergonomic as having the ability to selectively run a number of tests across modules and across files.

### References
Jest allows multiple tests to run with [`test.only`](https://jestjs.io/docs/en/api#testonlyname-fn-timeout).

**Comment by trentmwillis** [comment]
Thanks for opening this and providing a possible implementation. I'd prefer to do something like Jest and just expand what `only` does (rather than introducing additional methods).

I'm not sure I'd actually qualify this as a breaking change. Technically, it changes behavior, but it is not backwards-incompatible if a test suite were to be using `.only` currently. Additionally, `.only` isn't intended to be committed to codebases (there's even [an eslint rule for it in the eslint-plugin-qunit](https://github.com/platinumazure/eslint-plugin-qunit/blob/master/docs/rules/no-only.md)).

**Comment by ventuno** [comment]
Thanks for the feedback @trentmwillis. I agree with you that in general this _should not_ be a breaking change, but in my experience things that _should not_ happen always end up happening and people might be counting on `only` to keep working the way it is documented.
On top of that, please consider that [`no-only` seems to have issues at the moment](https://github.com/platinumazure/eslint-plugin-qunit/issues/79).

As a way to mitigate possible issues, perhaps we could introduce a configuration parameter like `legacyOnlyBehavior` so that people can bring back the old behavior if needed?

Regardless, I trust your judgement as you definitely know more than I do about QUnit and its users.
I can easily update https://github.com/qunitjs/qunit/pull/1435 to modify the way `only` behaves instead of adding a new method. Just let me know what is the preferred approach.
