### ISSUE TITLE
What to do with assert.ok/assert.notOk?

### ISSUE THREAD

**Issue by ventuno** [qunitjs/qunit#1450]
Following up on https://github.com/qunitjs/qunit/pull/1445#issuecomment-647052009 and the general conversation in https://github.com/qunitjs/qunit/issues/1444.

In https://github.com/qunitjs/qunit/pull/1445 we introduced `assert.true`/`assert.false`. We also discussed the possibility of discouraging the use of `assert.ok`/`assert.notOk` in the official documentation (see: [`assert.ok`](https://api.qunitjs.com/assert/ok) and [`assert.notOk`](https://api.qunitjs.com/assert/notOk)).

References:
* [QUnit anti-patterns](https://timotijhof.net/posts/2015/qunit-anti-patterns/);
* [`eslint-plugin-qunit` `no-assert-ok` rule](https://github.com/platinumazure/eslint-plugin-qunit/blob/master/docs/rules/no-assert-ok.md).

To update:
- [ ] All documentation should stop using `assert.*ok` in its examples (example [`module`](https://api.qunitjs.com/QUnit/module))
- [ ] All tests should stop using `assert.*ok` and use `assert.true`/`assert.false`/`assert.strictEqual` instead (example [`module-only` test](https://github.com/qunitjs/qunit/blob/master/test/module-only.js))

@Krinkle, @trentmwillis: thoughts?

**Comment by trentmwillis** [comment]
Seems reasonable to me. Maybe even deprecate + remove for QUnit 3.0.

**Comment by raycohen** [comment]
Kind of related, is loose equality still the right choice for assert.equal? Any chance we could make `assert.equal` strict in 3.0?

**Comment by Krinkle** [comment]
@raycohen I'm hestitant to do that because of the [CommonJS spec](http://wiki.commonjs.org/wiki/Unit_Testing/1.0) (which was on QUnit) and its implementation elsewhere, such as Node.js.

Small divergences from that are hard to avoid, but I think `assert.equal` vs `assert.strictEqual` is not important enough in the grand scheme of things compared to the long-term impact that would have on setting expectations and providing familiarity to users. Both new ones that may benefit from Node experience, or knowledge acquired through tutorials elsewhere, as well as exising users.

Having said that, I'd be open to a conversation with some of the Node.js folks (and perhaps CommonJS) to see if we could agree on a second revision to the spec in which we might decide on this as well as some other minor diferences.

**Comment by Krinkle** [comment]
@ventuno Let me know if you'd like to help with updating tests and/or docs. I'd like to complete this before releasing 2.11 and `assert.true` to avoid confusion. I'm aiming for mid or late August. I can give it a go as well, but let me know in a week or so if you'd like to do that :)

**Comment by ventuno** [comment]
Thanks @Krinkle. I'll try to take care of this in the next couple of weeks :-).
