### ISSUE TITLE
Deprecate QUnit.extend

### ISSUE THREAD

**Issue by smcclure15** [qunitjs/qunit#1491]
I was suprised to see the `QUnit.extend` API still fully supported, or at least not marked deprecated.
Would the native `Object.assign` not suffice, and QUnit can back away from this redundant implementation/support?

* [ ] Mark `QUnit.extend` as deprecated in code.
* [ ] Update documentation page.

**Comment by Krinkle** [comment]
`Object.assign` was introduced as part of the ES6 spec and is still relatively new. QUnit offer broader support since its implementation is relatively simple and this allows developers to decide what their supported markets are, without being limited by developer tooling.

At this point, we support IE9+. When we require Edge 12+, we can use `Object.assign()` internally.

However, I would support soft-deprecating this method in the public API since it is indeed only meant for internal usage. Then in the upcoming QUnit 3 release, it can become a private utility method.
