### ISSUE TITLE
Prevent navigating away

### ISSUE THREAD

**Issue by amk221** [qunitjs/qunit#1519]
Forgive me if this is a daft idea. Could QUnit utilise `onbeforeunload`, to create a failing test if a hyperlink was clicked for example, that would ordinarily cause the test suite to be exited.

**Comment by amk221** [comment]
For some context, there is a long standing [issue](https://github.com/testem/testem/issues/1021#issuecomment-732451524) where tests run via testem cause a browser timeout - this can happen if a test has accidentally, programmatically clicked a hyperlink thereby leaving QUnit mid-test.

**Comment by amk221** [comment]
A catch for this could be implemented in a test helper (i.e. in `click` - and _not part of QUnit).

```javascript
test(async function() {
  await visit('/');
  await click('.my-link');
});
```

**Comment by ro0gr** [comment]
Just adding a use case.. Redirect/reload can also occur for some other reason, e.g.  submitting a form which has a submit handler broken. In this case it'd just reload the page and restart the whole suite again and again. So 
I think checking the links only would not fix the underlying problem.

I suspect there is no easy/reliable way to check if that redirect was initiated by user(F5) or if it's triggered somewhere inside tests.

**Comment by amk221** [comment]
Ah yes good point. In that case it makes more sense to pursue the test helper avenue.

**Comment by Krinkle** [comment]
I'd support addition of something like this for the HTML page.

I do wonder though, from an automation perspective, this _should_ already not cause loops or false positives. I don't know off-hand how Testem works internally, bit I assume it'd be similar to the Karma and Puppeteer runners, which mount to a specific page. If that page closes, crashes, reloads, navigates etc. I'd expect those to already detect this and fail the test for having stopped before the "done" event.

So by way of defense in-depth, I think this should also be looked into as something the runner(s) should accomodate internally. We can still also handle it within QUnit for when you're debugging or running tests by hand from an HTML file.

**Comment by Krinkle** [comment]
I briefly looked into a few different ways to approach this and the sense I'm getting is that this isn't going to be a simple add-on that just disables or spies a few APIs because browsers intentionally make it difficult/impossible to craft a page such that you cannot leave it. Thus, this would involve heavy modification of the runtime environment, the `window` object, and other aspects of the DOM API, such that I expect it to be observable by application code and thus no longer be a neutral and useful target to run cross-browser tests in. The behaviour would also vary across browsers, change over time as browsers improve, and likely still leave gaps in its coverage.

I believe I do understand the problem, and think it makes sense for some applications to catch this issue explicitly if their application is especially likely to regress in a way that accidentally does this. Perhaps the code for that could be centralised in a utility function which your test suite could then mock from a `before` module hook. That way, the test would fail in a way that neatly describes what went wrong and where.

If the `beforeunload` event would work for your use case, you might be able to use [before/after](https://api.qunitjs.com/QUnit/module/#options-object) hooks to achieve the desired behaviour.

```js
QUnit.module('my component', function (hooks) {
  function onLeave() {
    throw new Error('Unexpected navigation');
  }
  hooks.before(function () {
    window.addEventListener('pagehide', onLeave); window.addEventListener('beforeonload', onLeave);
  });
  hooks.after(function () {
    window.removeEventListener('pagehide', onLeave); window.removeEventListener('beforeonload', onLeave);
  });

  QUnit.test('example', function (assert) {
    location.href = 'foo';
  });
});
```

Note that this would not prevent the navigation. It would emit a global failure, and then the browser continues to navigate away. The test runner of choice should then detect and react to that happening ideally so as to not get stuck or time out.

I'm closing this for now as it seems best for the simplicity and debuggability of other tests to not go down this path. But I'd be happy to help test runners catch this issue if they don't already, and to add any affordances they might need in QUnit itself.
