### ISSUE TITLE
Restore watch mode for QUnit development

### ISSUE THREAD

**Issue by ventuno** [qunitjs/qunit#1581]
Moving the conversation from https://github.com/qunitjs/qunit/pull/1580 here.

QUnit used to have a "watch mode" ([`npm` `dev` script](https://github.com/qunitjs/qunit/blob/main/package.json#L86)) that re-built sources and re-run tests as the sources changed. This a pretty common practice in many code bases, for example an [Ember application can run in watch mode (`ember test --server`)](https://guides.emberjs.com/release/testing/#toc_how-to-run-tests).

In https://github.com/qunitjs/qunit/pull/1580 I tried to fix the existing issue (e.g.: the absence of the `build` task in `grunt`), but it seems like we may want to consider alternative solutions instead.

[@Krinkle's suggested solution](https://github.com/qunitjs/qunit/pull/1580#issuecomment-815145744) is to:
1) run the `rollup` command in watch mode (`rollup -c -w`) so that sources are automatically rebuilt when files change;
2) run QUnit in watch mode as well (I am assuming we would be running it using `bin/qunit.js`?).

I would personally prefer one command which starts both, just because it's easier and that means that we only need one terminal (window/tab/section depending on your individual set up) to run in watch mode which is what probably most developers would expect.
I'm also unsure how we would be building the `css` files (which I believe are normally just copied into a different folder?).

Any thoughts?

**Comment by Krinkle** [comment]
I like using Rollup's own watch mode, mainly because that is substantially faster. Running rollup anew each time takes multiple seconds and so significantly eats away from the added value of runs starting automatically as you work and ideally finish before or without switching contexts. This is one of the reasons I never used our "dev" script. It does too much every time (new build, all CLI tests, all browser tests) so I don't find it faster than narrowly running explicitly what I need from time to time.

Using one command is definitely easier and I'm not opposed to that. However, using one command often means using yet another file system observer to then invoke fresh invocations of build/tests, which I don't find particularly useful per the above.

Having said that, I was very quick to remove it and did not realize others might find it useful exactly as it was. I don't oppose restoring it in whatever shape you find useful right now. Happy to accomodate it that!

Alternatively, if you'd like to help with perhaps a more clever approach, I could use the help on that as well. Perhaps we could have a little script that spawns rollup watch and qunit watch side-by-side, from the same npm run command?

**Comment by ventuno** [comment]
@Krinkle finally found some time to work on this:
1) as you recommended, I'm letting `rollup` (`-w -c`) watch for changes and re-build (doing it via the JS API);
2) I really want to be able to serve tests at the same time, for this reason, I created a tiny web server just for that. I know in [RELEASE.md](https://github.com/qunitjs/qunit/blob/main/RELEASE.md) we recommend to use `python3 -m http.server 4000` to run tests, but I figured a `node` server would make more sense in this context.

Alternatively, I was thinking of adding a new `--serve`/`-s` CLI argument that would allow to run the server. That's probably a separate conversation though.

Thoughts?
