### ISSUE TITLE
[Request] Disable the requirement for two factor auth ( 2FA ) to become/remain a qunitjs organisation member

### ISSUE THREAD

**Issue by shlomif** [qunitjs/qunit#1591]
Hi all!

Please disable the requirement for two factor auth ( 2FA ) to become/remain a qunitjs organisation member. I don't believe in the effectiveness of paranoid security ( see https://www.shlomifish.org/philosophy/philosophy/putting-cards-on-the-table-2019-2020/#fear-is-path-to-dark-side ). I tend to be forgetful and may misplace my smartphone, and in that case would rather not lose access to my github account (most of whose repositories are [deliberately kept public](https://www.goodreads.com/quotes/574706-only-wimps-use-tape-backup-real-men-just-upload-their) ).

If not, I'll have to retire as a qunitjs organisation member, and will have to contribute only using issues/comments and pull-requests/etc.

Regards,

-- Shlomi

**Comment by Krinkle** [comment]
@shlomif

I agree with much of your sentiment, I think, but I do believe 2FA provides meaningful account security.

I understand your frustration, and in terms of smartphones especially, I too would like my phone to be unworrying of loss (disposable, basically). There are a number of ways to get there, which have worked for me in different cases. One is to note your backup scratch codes. These can be kept digitally or on paper. Another is to use TOPT instead of SMS (seems preferred more generally, also for security). These app configurations can be backed up and restored. Another way is to add your TOPT to a desktop application rather than a mobile app. KeeWeb is an example of a password manager with built-in TOPT support, for example. There are numerous other such apps. 

Any measure one takes should be proportional and meaningful in relation to the risk it is meant to mitigate. For my personal repos, I don't feel the need for 2FA on the/my account's access to it. For QUnit, however, I think the risk of password brute force or email compromise on maintainer's accounts, justifies a second factor authentication as responsible measure on their part. That doesn't make compromise impossible, as no security measure is perfect, and it's not like the repo is the single point of failure (there's still the website, CDN, and npm registry). But, the repo is a very visible part of it that I'd like to at least prevent general non-targetted attacks on.

If there was a way for me to require 2FA for repo committers specifically, and specific to this repo, without requiring it for non-commit pemissions and for other repos, I would. Unfortunately, GitHub does not appear to offer this option at this time.

I'm keeping this open to give it some more thought later and to encourage others to chime in if they have thoughts on the matter. Thanks for contributing!

**Comment by smcclure15** [comment]
I'm empathetic and agree it's a nuisance, but multi-factor auth has become the norm for me for the last few years. I need my phone to even VPN into my day job, so this requirement is really nothing extra for me these days. Not saying it's painless, just an accepted habit and state of things.

**Comment by shlomif** [comment]
As the consensus seemed to have been **for** requiring 2FA, I left the qunitjs organisation ( and later disabled 2FA on my GH account ). Sorry for looking a gift horse by its mouth, but note that I may remain active as an underprivileged contributor.

This issue may be closed as far as I'm concerned.
