### ISSUE TITLE
Async `QUnit.module` bodies

### ISSUE THREAD

**Issue by xmo-odoo** [qunitjs/qunit#1597]
This is a feature request, possibly related to #1568 and #978

## Tell us about your runtime:

* **QUnit version**: 2.9.1 (but I checked the changelog and nothing related to this seems to have been added since)
* **Which environment are you using? (e.g., browser, Node)**: browser
* **How are you running QUnit? (e.g., QUnit CLI, Grunt, Karma, manually in browser)**: Chrome Devtools Protocol

## What are you trying to do?

Generative table-based tests, something along the lines of #1568 *but* the tables (the test suite / module definitions if you will) are defined in external files.

Currently each file yields a test, but in reality each file is composed of multiple semi-independent tests, so ideally each file would be a submodule and each test would be, well, a test. However since the *suites* are files they need to be loaded asynchronously, and it doesn't look like `QUnit.module` supports asynchronous bodies (nested scopes).

Not too sure how to create a "clean" reproduction,

```js
QUnit.module('mod1', async () => {
    console.log('mod1: before');
    await Promise.resolve();
    console.log('mod1: after')
    QUnit.test('test', () => {
        assert.expect(0);
        console.log('mod1.test');
    });
});
QUnit.module('mod2', () => {
    console.log('mod2');
    QUnit.test('test', () => {
        assert.expect(0);
        console.log('mod2.test');
    });
})
```
kinda shows the issue: you can see in the console that `mod2`'s body runs before `mod1` is done collecting.

## What did you expect to happen?

* that modules collection support asynchronous bodies
* or that asynchronous module bodies generate an error

## What actually happened?

The rest of the module body runs at the first opportunity after the synchronous collection is done, and things get odd.

**Comment by raycohen** [comment]
Related: https://github.com/platinumazure/eslint-plugin-qunit/blob/master/docs/rules/no-async-module-callbacks.md

**Comment by Krinkle** [comment]
I agree with @raycohen. For one-time async setup as in the issue description, our solution is to use use `hooks.before()`, which behaves identical to what an async module definition would be. `hooks.beforeEach()` work as well, but runs more often (before each test, instead of once for the test module).

@raycohen Yeah, a warning in 2.x sounds good to me.

**Comment by Krinkle** [comment]
@xmo-odoo I agree your use case is important, and believe it is best solved by using an async `hooks.before()`. I'll close this for now, but free free to message back any time if you think there may've been a misunderstandin or if it doesn't work as expected. Thanks!

**Comment by xmo-odoo** [comment]
@Krinkle 

> I agree your use case is important, and believe it is best solved by using an async `hooks.before()`. I'll close this for now, but free free to message back any time if you think there may've been a misunderstanding, or if the hook doesn't work for your use case. Thanks!

The issue with this is, as far as I can tell the `before` hooks are still plugged into the tests run (which makes sense, even module-level fixtures should not run if no test ii selected).

This means it's not possible to generate *test case*, only to have a single test making use of the generated table. At which point moving the table generation into a hook is not really useful[0], you might as well save yourself the trouble and leave it in the test.

I guess I should have provided a clearer case of what I was looking for, rather than the issue I found when digging. Basically this:
```js
QUnit.module('sum', function () {
    const table = [
        [[-1, 1], 1],
        [[1, 1], 2],
        [[1, 2], 3],
        [[2, 2], 4],
    ];
    for (const [[a, b], c] of table) {
        QUnit.test(`${a} + ${b} == ${c}`, (assert) => {
            assert.equal(add(a, b), c);
        });
    }
});
```
provides a nice report with the subtests clearly identified, and if one of the subtests fails it's NBD there's a clean report for that subtest and the rest runs fine:
```
not ok 1 sum > -1 + 1 == 1
  ---
  message: failed
  severity: failed
  actual  : 0
  expected: 1
  stack: |
        at Object.<anonymous> (/tmp/qunit-test/test/thing.js:12:20)
  ...
ok 2 sum > 1 + 1 == 2
ok 3 sum > 1 + 2 == 3
ok 4 sum > 2 + 2 == 4
1..4
# pass 3
# skip 0
# todo 0
# fail 1
```
As far as I  can tell (but again I might have missed something), this is not achievable if `table` requires fetching something asynchronously (e.g. a file, from a browser), because the `before` hook doesn't run before module bodies (which again I agree makes sense):
```js
QUnit.module('xxx', {
    before() {
        this.table = ...;
    }
}, function () {
    // `this.table` is undefined here
    QUnit.test(..., function (assert) {
        // this.table is defined here
    });
});
```
The issue is one of visibility and reliability for the generated test cases: this makes subtest failures (different "rows" of the table) separately visible and reported to the runner, and provides built-in isolation between the table rows (at least insofar as they're actually independent, obviously if they update globals and don't cleanup there are issues but at least the failure of one will not prevent running the rest).

I hope this is clearer than the original message as to what the intent was?

Prior art for this sort of features:

* [parametric tests](https://docs.pytest.org/en/stable/parametrize.html) 
* [subtests](https://docs.python.org/3/library/unittest.html?highlight=subtest#subtests),

Regardless, I'm happy enough if qunit 3 warns clearly on async modules

[0] note: here I'm talking about the table driving the test, if the table only provides data which can be used by multiple tests then obviously the hook is a better approach

**Comment by raycohen** [comment]
@xmo-odoo Is there a reason you can't do the async work prior to the module callback? Before any modules or tests are defined? For example: https://codepen.io/raycohen/pen/mdONpgB

**Comment by xmo-odoo** [comment]
@raycohen 

> Is there a reason you can't do the async work prior to the module callback? Before any modules or tests are defined? For example: [codepen.io/raycohen/pen/mdONpgB](https://codepen.io/raycohen/pen/mdONpgB)

Mostly that it's part of a much larger test suite, and this would need to be a global change to add this sort of feature, but here it was mainly that I tought it would work then I spent some time trying to understand why it didn't, before figuring out that it was not supported. Hence me being quite OK with getting a clear error that I'm trying something stupid my dumb brain just made up.

**Comment by Krinkle** [comment]
@xmo-odoo

The tricky bit is that JS test frameworks generally have a fairly deep assumption of knowing what tests exist, before executing them. First the test suite files load, and then we execute all the tests (or only the tests asked for, e.g. if filters or reruns are applied). When a filter is applied, the framework should give feedback quickly. This is why all that happens during the registration phase is to call `module()` with a name, run any closure, and process the calls to `test()` with a name. That's it. Nothing else runs yet. After that, the system know which module names and test names exist, how many, and then can start executing and counting toward that.

While we embrace asynchronisity internally, and in all public APIs during test execution, we don't currently allow it during the registration phase. If we were to allow this (meaning QUnit would remember that this module body was async and remembers not to render any UI or execute tests until it settles), that brings up other issues as well. For example, do we allow other modules to load meanwhile? Naively, that would happen by default, but that means you'll end up with an indeterministic registration order which may be undesirable. On the other hand, it seems that we'd be forced to hold back anything else because right now `QUnit.test()` adds to the "current" module, so if you have any modules and tests that don't use a module function, they would end up being parented under the wrong module. There isn't a way to distinguish those calls from the closure's calls. (This would be solved by https://github.com/qunitjs/qunit/issues/978, which is happening soon.)

-------

> Generative table-based tests, something along the lines of #1568 _but_ the tables (the test suite / module definitions if you will) are defined in external files.
> 
> Currently each file yields a test, but in reality each file is composed of multiple semi-independent tests, so ideally each file would be a submodule and each test would be, well, a test. However since the _suites_ are files they need to be loaded asynchronously, and it doesn't look like `QUnit.module` supports asynchronous bodies […]

I understand the use case and agree it seems nice to integrate your data structure completely using the test report's own grouping concepts (e.g. modules and tests). However, in the long run I think this tends to make things more complicated and if there's anything I've learned in the realm of testing, it's that tests aren't where you want complications to exist. Any time spent at all trying to understand the test itself, is time that could've been spent understanding the purpose of the test and your source code instead.

So, while I agree with your desire in isolation (and have at times felt the same), I believe the following compromises may in fact be better / more ideal in the long run. Not all these will feel right in all scenarios, but I hope one of them appeals. (Note, I'm aware you probably have a working alternative already, and perhaps none of this is new, but I figured I'd write it up anyway to have something to refer to since this isn't an uncommon question!).

1. One "test" per data file.

This is the most straight-forward to implement, but you'll likely encounter these two caveats at some point:

* Lots of assertions in a single "test". Not bad by itself, but when one of them fails you'll want to know which "case" caused it given that the line number probably won't tell you if that line is inside a for-loop of sorts. A natural first step is to e.g. prepend to the assertion messages, a description or identifier that would otherwise have been the name of each generated test.
* Filtering and re-running is limited to this "test" as a whole. Depending on how fast this is, that may or may not be bothersome.

2. One "test" per test case.

If you can afford to code within your test suite the identified test cases, then you can still get the structure you want at the cost of doing so explicitly. Each test would naturally exist exactly how you want it. You can, if wanted, re-use code between them through a utility function and/or by definining the tests within a loop as decribed in #1568. The difference would be that you fetch your data file inside the test function instead of outside of it.

Depending on what seems more efficient you can either split up the test files, or re-use the same one and have perhaps a utility function that caches the response after the first call.

If you're able to inject some amount of data into your test runner, you could e.g. inject which cases to expect to help reduce the amount of duplication. 

3. Synchronously.

If you're writing in Node.js, or if you don't mind using deprecated XHR async=false, you could actually do exactly what you originally set out to do, but synchronously. This does of course have the downside of having the expected downsides of that, which is a slower start up when re-running or filtering other tests.

4. Executable data.

If the data files exist primarily to serve your test suite, then perhaps you could generate them as `.js` files instead of `.json` files, and have them assign something like `window.MYAPP_FOO_TESTS`. Loading it depends on the test runner you use. In HTML, it'd be a script tag before the test file's script tag. In most CLI runners, it'd be one of the files you specifify as "bootstrap", "setup", or "require" file to load before the tests. This has the benefit of allowing the browser to download them in parallel, but still execute as normal in a consistent and fast way at run-time without any explicit asynchronisity in the registration phase.
