### ISSUE TITLE
Is coveralls badge pointing to correct branch?

### ISSUE THREAD

**Issue by smcclure15** [qunitjs/qunit#1602]
With #1590, I had hoped to finally get us in the "green" with a 90%+ coverage metric.
That does look like it hit 90+, though in the `refs/heads/main` branch:
https://coveralls.io/github/qunitjs/qunit?branch=refs/heads/main

Should the default branch there be `main`, or `refs/heads/main`? The `main` branch doesn't seem to update often, and certainly `master` is outdated.

**Comment by Krinkle** [comment]
It is set correctly to `main`. I've resynced the settings using the button Coveralls provide for this on their end but it made no differences.

I've contacted their support to advise on why the system is perceiving data submitted for the main branch as a custom branch, named `refs/heads/main`, instead of as being the main branch that it is.
