### ISSUE TITLE
Different results depending if `assert.rejects` is awaited or not

### ISSUE THREAD

**Issue by smcclure15** [qunitjs/qunit#1631]
## Tell us about your runtime:

* **QUnit version**: 2.16.0
* **Which environment are you using? (e.g., browser, Node)**: Node
* **How are you running QUnit? (e.g., QUnit CLI, Grunt, Karma, manually in browser)**: CLI

Here is my demo test. Note that the `getFlag` method is async, and fetches the `this.flag` value at a later time:
```js
QUnit.test('demo', assert => {

    class Util {
        constructor() {
            this.flag = 0;
        }
        async checkFlag() {
            const flag = await this.getFlag();
            if (flag === 1) {
                throw new Error('reason 1')
            }
            if (flag === 2) {
                throw new Error('reason 2')
            }
        }
        getFlag() {
            return new Promise(resolve => {
                setTimeout(() => {
                    resolve(this.flag)
                }, 0)
            })
        }
    }

    let obj = new Util();

    obj.flag = 1;
    assert.rejects(obj.checkFlag(), /reason 1/);

    obj.flag = 2;
    assert.rejects(obj.checkFlag(), /reason 2/);
});
```

Running that gives:
```
TAP version 13
not ok 1 demo
  ---
  message: failed
  severity: failed
  actual  : Error: reason 2
  expected: "/reason 1/"
  stack: |
        at runNextTicks (internal/process/task_queues.js:58:5)
        at listOnTimeout (internal/timers.js:523:9)
        at processTimers (internal/timers.js:497:7)
  ...
1..1
# pass 0
# skip 0
# todo 0
# fail 1
```
So by the time the first assertion resolved, the `flag` was already flipped to `2`, hence the mismatched reason.

BUT, if I make the test body `async` and do
```js
await assert.rejects(...)
```

(even just on the first reject line) it all runs fine:
```
TAP version 13
ok 1 demo
1..1
# pass 1
# skip 0
# todo 0
# fail 0
```

I could be convinced that this is on me, and this is JavaScript behaving completely as designed. I'm not sure if we can improve this part of it because then the framework is guessing at the intent.

But I do want to challenge at least the documentation of [`rejects`](https://api.qunitjs.com/assert/rejects/), as it does not reference a return value or how that should/could be leveraged, or where appropriate.

Possibly related: #1630

**Comment by Krinkle** [comment]
A promise or async method call passed to `rejects()`, is essentially required that the call is standalone or otherwise not overlapping/relying on other statements in the test function. E.g. separate instances, or passing data into the call.

When multiple async assertions share essential state in the same test, the order becomes relevant and thus one would have to use `await` to ensure the test waits accordingly (or in ES5, to return a promise chain).

Personally I tend to unwrap async code whenever possible, so as to handle it natively rather than in the test runner, for example:

```js
async function add(a, b) {
	if (typeof a !== 'number' || typeof b !== 'number') {
		throw new Error('Bad parameter type');
	}
	return Promise.resolve(a + b);
}

QUnit.test('add', async assert => {
	assert.equal(await add(1, 2), 3);
});
```

But as far as I can tell, this is not possible when asserting an expected exception. One would need to use `assert.throws()`, but await is always in relation to the nearest function, so we can't hide the asyncronous nature from `throws()`, thus `rejects()` has to be used, and thus you need to let the test runner wait for the result, then assert the result, and have the test function wait for both of those things. Thus `await assert.rejects()` is the appropiate pattern for that:

```js
QUnit.test("example", async assert => {
	assert.equal(await add(1, 2), 3);

	await assert.rejects(add(), /Bad parameter/);

	await assert.rejects(add(1, 'x'), /Bad parameter/);

	await assert.rejects(add(1), /Bad parameter/);
});
```

<https://codepen.io/Krinkle/pen/abWvoPj/right?editors=0010>

> it does not reference a return value or how that should/could be leveraged, or where appropriate.

Yep, it's relatively rare in my experience, but 100% this should be documented (and tested!).

**Comment by Krinkle** [comment]
Closing per https://github.com/qunitjs/qunit/pull/1636.
