### ISSUE TITLE
2.17.0 no longer throws an error in the browser runner when a filter does not match any tests

### ISSUE THREAD

**Issue by kategengler** [qunitjs/qunit#1651]
In the browser runner, v2.17.0 no longer throws an error when no tests match the filter.

### On v2.16.0 in the browser

The following is a result of tests run with a filter that matches 0 tests:

<img width="771" alt="Exception thrown in browser runner" src="https://user-images.githubusercontent.com/444218/132585282-f48fbd7b-1152-4c3f-903c-7c57a763c34a.png">

### On v2.17.0 using the browser:

No exception is thrown and the results are curious (`1 tests completed in [2] milliseconds, with 1 failed, 0 skipped, and 0 todo.
0 assertions of 1 passed, 1 failed.`)

<img width="922" alt="Browser runner results on 2.17" src="https://user-images.githubusercontent.com/444218/132585674-c72666d0-a3d6-45b8-9b99-06da919ff67d.png">

### On v2.17.0 using `qunit`

The exception is thrown: 
```
not ok 1 global failure
  ---
  message: "Error: No tests matched the filter \"foo\"."
  severity: failed
  stack: |
    Error: No tests matched the filter "foo".
        at done (/Users/katie/dev/experiments/qunit-repro/node_modules/qunit/qunit/qunit.js:2118:17)
        at advanceTestQueue (/Users/katie/dev/experiments/qunit-repro/node_modules/qunit/qunit/qunit.js:2025:7)
        at Object.advance (/Users/katie/dev/experiments/qunit-repro/node_modules/qunit/qunit/qunit.js:1980:7)
        at unblockAndAdvanceQueue (/Users/katie/dev/experiments/qunit-repro/node_modules/qunit/qunit/qunit.js:4295:21)
        at processTicksAndRejections (node:i
```

### Reproduction

See https://github.com/kategengler/qunit-repro and follow directions in README.md

### Tell us about your runtime:

* **QUnit version**: 2.17.0
* **Which environment are you using? (e.g., browser, Node)**: browser
* **How are you running QUnit? (e.g., QUnit CLI, Grunt, Karma, manually in browser)**: manually in browser, testem

**Comment by Krinkle** [comment]
@kategengler Thanks, this is a regression indeed.

I did anticipate one edge case where an error would become console-only, namely if you 1) have the test scripts in the HTML before the `<div id=qunit>`, and 2) there is an uncaught error before tests have begun (e.g. in the global scope between tests or in a top-level module closure). In that case it would previously queue a fake test to run after the UI is loaded and then insert the error, whereas now it tries to report it immediately which becomes console-only if there is no UI element on the page.

But, neither of those is the case in your example.

**Comment by Krinkle** [comment]
@kategengler Thanks, this is a regression indeed. There should definitely be something in the UI for that.

**Comment by Krinkle** [comment]
The error message is actually still rendered in the DOM. But, it has `display: none;` applied:

<img width="341" alt="capture" src="https://user-images.githubusercontent.com/156867/132595884-2435cf59-48e1-4daf-b9d8-276b5e089047.png">

The reporting to the console as `window.onerror` was previously a unintended side-effect of an internal issue. When QUnit reports an uncaught error (e.g. syntax error in app source before the tests begin, or otherwise outside test cases), it tries to render this as a "fake" test. But, if the reporter (e.g. ember-cli) was already informed of the tests having finished, then emitting another test would be invalid, and there it would sometimes get stuck, which is why the first example shows the the UI stuck at "Running..." with an uncaught error from QUnit internals.

@kategengler @stefanpenner I reviewed various reporters and CI integrations and thought it would not be a breaking change to report these as test failures (or TAP error) instead - only falling back to a global error if there is no other way. If this requires changes in ember-cli to accomodate or otherwise feels like it might make anything difficult or different from before, do let me know as that that is in no way intended. I'd be happy to revise this or pull it back out for now.

**Comment by kategengler** [comment]
@Krinkle A failing test should work with ember-cli / testem. In the test that started failing, the results were reporting back via with '0 tests, 0 pass, 0 fail' reported. I can try to make a more involved reproduction.
