### ISSUE TITLE
Eager DOM creation for module filter triggers delay in test execution

### ISSUE THREAD

**Issue by mixonic** [qunitjs/qunit#1664]
At the codepath [`toolbarModuleFilter` where `moduleListHtml` is called](https://github.com/qunitjs/qunit/blob/037505f3b6e9e15fb132279b3073113c66233d27/src/html-reporter/html.js#L418) the list of all modules in a test suite is iterated and a set of sibling `<li>` elements is created. For a given test suite, the number of nodes created may be fairly high (for example about 800 in a large codebase I maintain). When these are appended to the DOM, Chrome seems to trigger a slow frame after the append where some kind of internal bookkeeping for the DOM is handled.

This may manifest as a 5-15 second delay before tests run (in some cases worse). On the devtools timeline, it looks like this:

<img width="1270" alt="Screen Shot 2021-11-04 at 2 22 27 PM" src="https://user-images.githubusercontent.com/8752/140397773-5780d375-c731-4111-b703-bb76815c63ea.png">

In Firefox, this does not seem be reliably be an issue. I suspect there is a Chrome issue when there are a large number of sibling nodes in the DOM, but so far haven't been able to run that down.

Regardless, removing `moduleListHtml` causes the entire long task to go away. Re-writing the `moduleListHtml` function to manipulate DOM instead of generating HTML did not improve the issue.

In `toolbarModuleFilter`, the call to `moduleListHtml` is being run eagerly. It runs regardless of if the module dropdown is going to be opened. There are several paths forward to improving QUnit's load time (even absent the pathological issue in Chrome) that could be considered:

* The module filter should only ever show the top 20 modules. If the user needs a specific module, they can search.
* The module filter should not populate the contents of the dropdown until the box is interacted with.
* The module filter should never populate modules unless a search is happening.

I'm happy to land an upstream change. What approach, or what other approach, seems viable?

## Tell us about your runtime:

* **QUnit version**: 2.17.2
* **Which environment are you using? (e.g., browser, Node)**: Chrome Version 95.0.4638.69 (Official Build) (x86_64)
* **How are you running QUnit? (e.g., QUnit CLI, Grunt, Karma, manually in browser)**: Manual page load via Ember CLI.

**Comment by Krinkle** [comment]
Thanks for the report. I think within the QUnit 2.x series, in the interest of compatibility, I'd recommend the second approach:

> The module filter should not populate the contents of the dropdown until the box is interacted with.

I'll also take a look this weekend to reproduce the issue in Chrome. There's a very small feeling that Chrome may be misattributing this, which I'd like to rule out, but the improvement would be welcome either way. If confirmed, I'd also like to report it to upstream Chromium if you haven't already.

Thanks again!

**Comment by Krinkle** [comment]
OK. This is definitely slow to load in Firefox as well, and there isn't anything else going on in this example test suite, so it's gotta be the module count.

I made a few related changes to the performance of this at https://github.com/qunitjs/qunit/pull/1685.

@mixonic I propose we do both of the following:
1. Yes, let's not bother generating it onload. We can defer `moduleListHtml` to the (first) searchFocus call.
2. Yes, let's limit the absolute count.

I'd aim for 50 rather than 20, and to keep it populated on open (similarly, upto 50 instead of unlimited). This keeps the free navigation we have today that I think is valuable for beginners, to scroll and explore when uncertain. For the simple cases when one has under 50 modules in total, I think it's benefitial to the experience to have the list there right away and select what you need. (I don't expect to make use of that myself.)

We can ignore the compat concern from my previous comment. This would apply to themes, but that's for styling. I'm not aware of an (undocumented) expectation in plugins or themes relying on suggestions being in the DOM by default. And in terms of the results being complete, prior to #1685 we showed relatively few suggestions, and I actually increased it by removing the scoring threshold. To avoid making large test suites feel even slower, I think we should bring back some limitation to the results prior to releasing that change, but this time by absolute count rather than by fuzzy scoring threshold.

**Comment by mixonic** [comment]
I did take a stab at this while waiting for triage here: https://github.com/mixonic/qunit/commit/95908906622f5b8ac67bffb70fe3a42c1ff6afad it seems pretty simple. Via the branch at https://github.com/mixonic/qunit/commits/mixonic/lazy-dropdown-built we've been using that successfully.

Funny enough, we always found Firefox fast. It was only for a subset of our Chrome users that it was extremely slow (never for all).

**Comment by Krinkle** [comment]
For future reference, here is a before and after of the usability and design changes I made in preparation for fixing this bug. The code changes were committed separately (design and prep in 06c39517a17b015faa1849828b04f7b48ea049ea, actual bug fix in 12224261c621532b38d8f3c90dca0174f8242ca5).

| | Before | After
|--|--|--
| Keyboard navigation (animation) | ![Kapture before](https://user-images.githubusercontent.com/156867/163740098-26e9bfde-cdac-4035-99b9-19146b2d63e4.gif) | ![Kapture after](https://user-images.githubusercontent.com/156867/163740122-e1af8c35-35c8-4596-a367-1f7d2f904e75.gif)
| Button and list design | <img width="748" alt="Before" src="https://user-images.githubusercontent.com/156867/163740197-abcf8f9a-f440-4a02-ac3e-d345b38268c3.png"> |  <img width="748" alt="After" src="https://user-images.githubusercontent.com/156867/163740193-df44e637-dab4-4915-aec4-dd02905914ec.png">
| Selection and cursor | <img width="455" alt="Before" src="https://user-images.githubusercontent.com/156867/163740288-d0e45308-d714-43a9-bf9c-1c198b5e55ba.png"> | <img width="458" alt="After" src="https://user-images.githubusercontent.com/156867/163740299-9fb2b8ee-02ab-4dc3-993b-0d70daca8005.png">
| Placeholder | ![Before](https://user-images.githubusercontent.com/156867/163740326-4254ef7b-0ced-424a-a2ae-2f209a65f0b8.png) | ![After](https://user-images.githubusercontent.com/156867/163740324-dd5f9b8c-913f-493c-be0d-a58b9a9641f2.png)

Highlights:
* There is no longer a "dead" tab target between the action buttons and the first search result (see above animation).
* The focus ring for the "Apply" button is no longer clipped on two sides by hidden overflow (see above animation).
* Previously selected choices are always shown, even if not matched by current search input.
* More breathable design for results and buttons. Cursor background is bright instead of dark. Toolbar button no longer lost in the greyness of the background.
