### ISSUE TITLE
cli: disable default logging

### ISSUE THREAD

**Issue by ShaMan123** [qunitjs/qunit#1671]
## Tell us about your runtime:

* **QUnit version**: latest
* **Which environment are you using? (e.g., browser, Node)**: node
* **How are you running QUnit? (e.g., QUnit CLI, Grunt, Karma, manually in browser)**: qunit cli

## What are you trying to do?
I want to override the default logging of qunit
It isn't clear how to do so.
I do understand how to add logging.
My tests dump too much data and it becomes useless.

Used 
```
//  https://api.qunitjs.com/extension/QUnit.dump.parse/
QUnit.dump.maxDepth = 1;
```
But it's not enough

## Workaround
override assertions
```js
QUnit.assert.equal = function (actual, expected, message) {
  this.pushResult({
    result: actual == expected,
    actual: getLoggingRepresentation(actual),
    expected: getLoggingRepresentation(expected),
    message
  });
};
```

**Comment by ShaMan123** [comment]
I think a diff output for deepEqual is much more desirable instead of dumping actual and expected

**Comment by ShaMan123** [comment]
And if I'm at it coloring is an important feature (`chalk`)

**Comment by ShaMan123** [comment]
and this as well [QUnit.config.hidepassed](https://api.qunitjs.com/config/hidepassed/)

**Comment by Krinkle** [comment]
Thank for creating the issue. The `QUnit.dump.maxDepth` works as expected I believe, and is covered with tests as well. The `QUnit.dump` method is used by the HTML Reporter, where this works:

Example: <https://codepen.io/Krinkle/pen/yLPXmEo>.

The TAP reporter, as used in the CLI by default, doesn't yet ship a differ by default. The issue for that is https://github.com/qunitjs/qunit/issues/1412, and a a related proposal for assertion plugins to provide a custom diff to render certain domain-specific values in a more optimal manner (https://github.com/qunitjs/qunit/issues/1005).

**Comment by ShaMan123** [comment]
Another thing is that the cli should accept a `module` flag and set `QUnit.config.module` to the passed value
It's an easy fix, I would PR but I don't understand where the file is located.

**Comment by Krinkle** [comment]
I propose we try to use the same differ as we use in the browser and colorise it with kleur console sequences instead of HTML tags. The abstraction is there already. We may want to solve https://github.com/qunitjs/qunit/issues/1005 at the same time, eg produce the diff inside core instead of separately in HTML and TAP, and then have HTML/TAP only serialise they diff.

I'm tentatively closing this in favour of https://github.com/qunitjs/qunit/issues/1412, as my understanding is that having a diff and being able to use maxDepth is the desired outcome, not per-se the ability to disable logging.

If you do want to customise or replace logging entirely, one can use `--reporter` and/or pipe it to a generic TAP transformer that minimises output.

**Comment by ShaMan123** [comment]
> I'm tentatively closing this in favour of #1412, as my understanding is that having a diff and being able to use maxDepth is the desired outcome, not per-se the ability to disable logging.

Absolutely
