### ISSUE TITLE
qunit: command not found

### ISSUE THREAD

**Issue by matthewcornell** [qunitjs/qunit#1712]
Hi Folks. New to qunit and loving it. I am able to get tests to run in an html file I created for my project, and I am also able to run those tests via `npm test`. However, bash isn't finding the `qunit` binary, and I'd like to understand why. I hope this is an appropriate place to ask. Thank you!

## Tell us about your runtime:

* **QUnit version**: qunit@2.19.4
* **Which environment are you using? (e.g., browser, Node)**: Node (and browser)
* **How are you running QUnit? (e.g., QUnit CLI, Grunt, Karma, manually in browser)**: QUnit CLI

**Node and npm versions: Node.js v18.15.0 and npm v9.5.0**

## What are you trying to do?

Code that reproduces the problem: Trying to simply run the `qunit` binary in bash.

Steps:
1. Mac OS X 10.15.7
2. install nodejs 18.15.0 (includes npm 9.5.0) via package installer (node-v18.15.0.pkg)
3. verify those binaries work (they do: `node --version` -> v18.15.0 , `npm --version` -> 9.5.0 )
4. `npm install` to install qunit and its dependencies. package.json:
```json
{"type": "module",
 "devDependencies": {"qunit": "^2.19.4"},
 "scripts": {"test": "qunit"}}
```

5. run `npm test` -> works. output:
```bash
$ npm test

> test
> qunit

TAP version 13
ok 1 must have one or more componentModels
ok 2 some models had no forecast data
ok 3 not all forecasts had the same target_end_dates
ok 4 quantileArrays not all the same length
ok 5 check all array items are numbers
ok 6 one model
ok 7 two models
1..7
# pass 7
# skip 0
# todo 0
# fail 0
```

6. try to run `qunit` binary -> fails:
```bash
$ qunit
-bash: qunit: command not found
```

## What did you expect to happen?

Bash should be able to find `qunit` binary.

## What actually happened?

> "-bash: qunit: command not found"

## Here's the node_modules/qunit/ dir contents:
```bash
$ find node_modules/qunit/
node_modules/qunit/
node_modules/qunit//bin
node_modules/qunit//bin/qunit.js
node_modules/qunit//README.md
node_modules/qunit//package.json
node_modules/qunit//qunit
node_modules/qunit//qunit/qunit.css
node_modules/qunit//qunit/qunit.js
node_modules/qunit//LICENSE.txt
node_modules/qunit//src
node_modules/qunit//src/cli
node_modules/qunit//src/cli/run.js
node_modules/qunit//src/cli/require-qunit.js
node_modules/qunit//src/cli/find-reporter.js
node_modules/qunit//src/cli/require-from-cwd.js
node_modules/qunit//src/cli/utils.js
$ 
```

**Comment by Krinkle** [comment]
Hi @matthewcornell!

**What**

The `qunit` command is reported as not found because you tried to execute it as a "global" command, but QUnit is usually best to install "locally" in a project, not globally.

**Why**

In the Bash shell, when you run a command, the first "word" refers to the name or path of a program. When you refer to a program by its name only (such as `grep`, `node`, or `npm`; instead of `/usr/bin/grep` or `./bin/qunit`) then Bash will try to find a program by that name in the system-wide `/usr/bin` and `/usr/local/bin` directories (decided by the`PATH` environment variable).

I generally recommend that developers install tools like bash, Node.js and npm globally, and indeed that is what you have done. The choice to use QUnit (and which version) is specific to each software project, and you may be trying out multiple projects by multiple people. You might have a project in `~/Documents/foo/` that uses QUnit 1.x, and a project in `~/Documents/bar/` that uses QUnt 2.x. This is possible because each has their own `package.json` file that tells npm which version to install in the local `node_modules` directory.

**How**

When you run `npm test`, the npm tool creates a Bash context where the local `node_modules/.bin/` directory is temporarily included to your Bash PATH, so that it can execute the `qunit` command. If you've used other packages via npm, these will work the same way. I recommend using `npm test` and `package.json` so that you avoid accidentally making your project dependent on a program that you have installed on your computer globally, without declaring it in your local `package.json` file. That way, when you share your program with someone else, or when you work on it from another computer, it still works the exact same way.

**Answer**

You can experiment with variations of commands, without needing to edit package.json, by using the `npx` command. This basically says "pretend to be inside a package.json 'script' context". For example: `npx qunit -w` will run `./node_modules/.bin/qunit -w`.

**Comment by matthewcornell** [comment]
What an amazingly friendly, detailed, and clear message. Much appreciated 👍 !
