### ISSUE TITLE
Unable to filter for more than one exclusion

### ISSUE THREAD

**Issue by edwinbradford** [qunitjs/qunit#1802]
## Tell us about your runtime:

* **QUnit version**: 2.13
* **Which environment are you using?**: Chrome 130 (latest)
* **How are you running QUnit?**: Manually in browser using Karma 6.4.3

## What are you trying to do?
I am working on a fork of [VideoJS](https://github.com/videojs/video.js) which uses QUnit tests. Some of the tests are incompatible with my project so I am trying to exclude them in a `QUnit.config.filter`.

The names of two tests I'm trying to exclude are:

* audioOnlyMode(true/false) changes player height
* player height should match control bar height when audioOnlyMode is enabled

There is one example in the documentation for [filtering](https://qunitjs.com/api/config/filter/) multiple QUnit tests `/(this|that)/` but there is no example for excluding multiple tests and as I can not get it to work I am not sure if my syntax is correct.

Code that reproduces the problem:

```js
QUnit.config.filter = "!audioOnlyMode(true/false) changes player height|!player height should match control bar height when audioOnlyMode is enabled";
```
also as a regular expression:

```js
QUnit.config.filter = "!/audioOnlyMode\(true\/false\) changes player height|player height should match control bar height when audioOnlyMode is enabled/";
```

## What did you expect to happen?

The filtered QUnit tests should be excluded from the workflow. 

## What actually happened?

Both QUnit tests are still included. When filtering with a single exclusion such as that below, the exclusion works but the syntax I am using for multiple exclusions fails.

```js
QUnit.config.filter = "!audioOnlyMode(true/false) changes player height";
```

**Comment by edwinbradford** [comment]
It appears that without regex only one QUnit test is supported regardless whilst with regex, more than one QUnit test is supported and I am able to get filters without special characters to exclude both named QUnit tests.

With regex, no special characters and two QUnit tests works as expected:

````js
QUnit.config.filter = "!/player height should match control bar height when audioOnlyMode is enabled|on error, modalButtons should get the buttons if those are available/";
````

With regex, special characters and two QUnit tests does not work

````js
QUnit.config.filter = "!/audioOnlyMode\(true\/false\) changes player height|player height should match control bar height when audioOnlyMode is enabled/";
````

Without regex two QUnit tests does not work regardless:

````js
QUnit.config.filter = "!player height should match control bar height when audioOnlyMode is enabled|on error, modalButtons should get the buttons if those are available";
````

Without regex a single QUnit test with special characters works as expected:

````js
QUnit.config.filter = "!audioOnlyMode(true/false) changes player height";
````

With regex a single QUnit test with special characters does not work (with or without negation).

````js
QUnit.config.filter = "/audioOnlyMode\(true\/false\) changes player height";
````

Anyone have any suggestions how to negate both of my QUnit tests, one of which has special characters?

**Comment by edwinbradford** [comment]
Solved it, I had already figured out above that you have to use regex for multiple tests, the final problem was special characters which have to be escaped with a double backslash, not a single. The following filter excludes both QUnit tests.

````js
QUnit.config.filter =
  "!/audioOnlyMode\\(true\\/false\\) changes player height|player height should match control bar height when audioOnlyMode is enabled/";
````

**Comment by Krinkle** [comment]
@edwinbradford That's right. One point I would add is that, it's not exactly about multiple "tests", but rather about multiple "exclusion patterns".

```js
QUnit.config.filter = '!foo';
```

This will filter any and all modules and tests that contain the word "foo". This could be excluding 0 tests, 1 test, or 300 tests. There is no particular assumption that a filter will exactly match the full name of a single test.

```js
QUnit.config.filter = '!/foo|bar/`;
```

This will use `/foo|bar/.test(fullName)` in JavaScript, via [RegExp.test](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test), to check if the name matches the pattern. The pipe separate there is not something used by QUnit, but rather a feautre of JavaScript regular expressions in general. In this case that will filter (and exclude, per the `!`), any test name that contains "foo" or "bar".

As per regular expression syntax, the parenthesis indeed need to be escaped. And, given that the pattern is passed as a string, JavaScript requires two back slashes for that to be part of the string. You can observe this on the console in plain JavaScript as well, without QUnit:

```js
var x = 'hello';
console.log(x); // hello

var x = 'hello (foo)';
console.log(x); // hello (foo)

var x = 'hello \(foo\)';
console.log(x); // hello (foo)

var x = '\h\e\l\lo foo';
console.log(x); // hello foo

var x = 'hello \\(foo\\)';
console.log(x); // hello \(foo\)
```

When only one backslash is used, the string does not actually contain any backslash. It is never seen, because most characters, including most letters and parenthesis, are not special in JavaScript strings, so escaping them is redundant. The character that is special, is the slash, it is the slash that we want to escape. So the slash needs to be in front of... the slash. I hope that makes sense!

**Comment by edwinbradford** [comment]
Oh I see, thanks for taking the time to explain that, I have come across double slash escapes before but didn't understand when to use them. I hope this issue helps other less experienced developers like myself as I couldn't find other examples.
