### ISSUE TITLE
return QUnit.url on QUnit < 2.0.0

### ISSUE THREAD

**Issue by leobalter** [qunitjs/qunit#740]
Ref https://github.com/jquery/qunit/commit/d86d6c38991a82e2c534eacc03dd10eac1ca1e69#commitcomment-9471316

**Comment by shivamdixit** [comment]
@leobalter Can you please elaborate on the issue a bit?

**Comment by JamesMGreene** [comment]
@shivamdixit Leo removed an undocumented internal method that was publicly exposed in a minor/patch version, and it turned out some consumers were using it for extension purposes (see the link in Leo's original comment). So, per SemVer guidelines, we are restoring the method's public exposure in a `v1.x` release but can still choose to remove it in `v2.x`.

**Comment by shivamdixit** [comment]
@JamesMGreene Thanks for the clarifications. So QUnit.url method is still present in the current release? Is there anything that has to be done apart for removing it in `v2.x`?

**Comment by JamesMGreene** [comment]
No, `QUnit.url` was removed in `v1.17.0` and hasn't been restored yet, thus the reason for this issue being created for tracking purposes (and still open).

**Comment by shivamdixit** [comment]
Okay. I'm working on this.

**Comment by shivamdixit** [comment]
Is it fine if I restore:

```javascript
url: function( params ) {
		params = extend( extend( {}, QUnit.urlParams ), params );
		var key,
			querystring = "?";

		for ( key in params ) {
			if ( hasOwn.call( params, key ) ) {
				if ( params[ key ] === undefined ) {
					continue;
				}
				querystring += encodeURIComponent( key );
				if ( params[ key ] !== true ) {
					querystring += "=" + encodeURIComponent( params[ key ] );
				}
				querystring += "&";
			}
		}
		return location.protocol + "//" + location.host +
			location.pathname + querystring.slice( 0, -1 );
	},
```

and in `reporter/html.js` setUrl() definition, make a call to above function to remove redundancy?

**Comment by leobalter** [comment]
As this is used exclusively at the reporter, I would put this at the reporter. Basically you would need to set it here: https://github.com/jquery/qunit/commit/d86d6c38991a82e2c534eacc03dd10eac1ca1e69#diff-5b7e94e2a10b848c4ae4b539388f86aeR269

**Comment by jzaefferer** [comment]
We should keep in mind that the reason for "bringing this back" is the qunit-notifications projects, which already [implemented a workaround](https://github.com/dockyard/qunit-notifications/commit/44fd5456d94cc5d8aac298df7af3bde285531d88). Bringing `QUnit.url` back in a minor release, only to remove it again in 2.0.0 seems pretty pointless, since qunit-notifications likely would just have to stick with their workaround anyway.

Maybe @rwjblue or @amercier can chime in here.

**Comment by amercier** [comment]
@jzaefferer I would be happy to rollback our workaround and use QUnit's API instead since it's not DRY. However, I'm not aware of QUnit's chamber secrets regarding v2. If a lot of this are going to change and `QUnit.url` make no sense in v2 world, then it's pointless to rollback this change (which wasn't officially part of the API in the first place anyway). Let's move forward.

**Comment by jzaefferer** [comment]
Alright, thanks for chiming in! That confirms my guess that we need a long-term solution. Either we bring back `QUnit.url` and keep it, for we leave things as-is. Considering that the `generateQueryString` function you've added isn't exactly trivial, along with changes we keep making to generate URLs (like 01fcdd41eb7bbadc8c2783b25d746d49c69d945f), I vote for bringing back QUnit.url and documenting it properly as public API, with no intention to remove it.

**Comment by amercier** [comment]
:+1:

**Comment by jzaefferer** [comment]
@leobalter @JamesMGreene thoughts on this? See my last comment above for details.

**Comment by leobalter** [comment]
>  I vote for bringing back QUnit.url and documenting it properly as public API, with no intention to remove it.

:+1: 

If it's namespaced, I don't see why not shipping it.

**Comment by jzaefferer** [comment]
We should come up with a better name.

**Comment by leobalter** [comment]
Is it still necessary? Damage is done - my bad - but now I wonder (again) if it's still necessary.

**Comment by Krinkle** [comment]
`QUnit.url` became private in 1.17.0, so from what I can see this is obsolete now, right?

**Comment by trentmwillis** [comment]
I'm going to go ahead and close this. I see no reason for this to come back into the framework and back-porting it at this point feels a bit pointless.
